# Generated by Django 3.1.4 on 2021-01-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_auto_20210130_1628'),
        ('posts', '0005_auto_20210130_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='perfil.profile'),
        ),
    ]
