# Generated by Django 3.1.4 on 2021-01-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210130_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
    ]
