# Generated by Django 3.1.4 on 2021-01-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210130_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='user',
        ),
    ]
