# Generated by Django 3.1.4 on 2021-01-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20201213_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background',
        ),
    ]
