# Generated by Django 3.1.4 on 2021-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20210126_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
