# Generated by Django 3.1.4 on 2021-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20210130_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
